FROM openjdk:17-alpine

# expose the mongodb port to let communication with another containers
EXPOSE 8080

WORKDIR /usr/app

ARG JAR_NAME=product-service-0.0.1-SNAPSHOT.jar
COPY ./target/$JAR_NAME ./product-service.jar

CMD ["java", "-jar", "./product-service.jar"]