FROM maven:3.9-amazoncorretto-17 as builder

WORKDIR /usr/app

COPY . .

RUN mvn clean package -DskipTests

FROM openjdk:17-alpine

# expose the tomcat port to let communication with another containers
EXPOSE 8080

WORKDIR /usr/app

ARG JAR_NAME=product-service-dev-SNAPSHOT.jar
COPY --from=builder /usr/app/target/$JAR_NAME ./product-service.jar

CMD ["java", "-jar", "./product-service.jar"]