name: build-and-test-changes
run-name: ${{ github.actor }} has pushed a change.
on: [push]

jobs:
  mvn-build:
    runs-on: ubuntu-latest
    name: mvn build
    steps:
      - uses: actions/checkout@v2
      - name: Set up jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'
      - name: Build maven
        run: mvn clean package -DskipTests